_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: Cyclic Starter Bot
features:
  bot_user:
    display_name: Cyclic Starter Bot
    always_online: false
oauth_config:
  scopes:
    bot:
      - chat:write
      - channels:history
      - groups:history
      - im:history
      - mpim:history
      - app_mentions:read
settings:
  event_subscriptions:
    request_url: https://some-subdomain.cyclic.app/events
    bot_events:
      - app_mention
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
